### ISSUE TITLE
settings are difficult to change

### ISSUE THREAD

**Issue by dynamicbutter** [flame-engine/forge2d#22]
There are some tunable limits in src/settings.dart.  I couldn't find a way for the caller to pass in new values for these.  So I created a fork with my values.  I realize these limits aren't meant to be changed often but I have found it useful.  The presenting case was to increase maxTranslation in order to verify the cause of my body's velocity limit was this parameter and not something wrong in my logic.  It would be very useful to be able to tune these settings without forking a new version.

**Comment by spydon** [comment]
I don't think we want to make `maxTranslation` tunable, since users will think that it is a good idea when they have velocity problems, instead of changing the scale which is the proper solution. Do you have any other limits in `settings.dart` that you would like to have tunable?

**Comment by dynamicbutter** [comment]
I'm not dying for this, but having access to all the original tuning parameters is generally looked upon favorably.

**Comment by spydon** [comment]
Which are those then? I'm guessing that when the dart port was ported off jbox2d these were not configurable.

**Comment by dynamicbutter** [comment]
Just the ones in src/settings.dart, if there are no tunables in there just close this

**Comment by spydon** [comment]
I made them all mutable now, but added a note, hopefully that will get only users that know what they are doing to change the values. :)

**Comment by spydon** [comment]
Released `0.8.1` with this change.

**Comment by dynamicbutter** [comment]
👍
