### ISSUE TITLE
Accessing Mutable Settings

### ISSUE THREAD

**Issue by mjordan56** [flame-engine/forge2d#27]
Now that velocityIterations and positionIterations have been moved to settings.dart, how are users of Forge2d suppose to access these mutable settings? It seems like there should be getters and setters for these mutable settings. This is also true for the mutable setting velocityThreshold. All of the other values in settings.dart are immutable. If getters and setters are not desirable, then I believe setting.dart should be exported in forge2d.dart so users of the library can access the variables.

**Comment by spydon** [comment]
It should indeed be exported, must have missed that.

**Comment by spydon** [comment]
Released `0.8.1` with this change.
