### ISSUE TITLE
sensor-sensor collision

### ISSUE THREAD

**Issue by supagu** [flame-engine/forge2d#29]
should I be able to detect sensors colliding with other sensors?
I can successfully detect contacts between a physics body and a sensor.

I am using body.setPosition to move one of my sensors so not sure if that is a problem with the way I am moving it or if somehow sensors do not interact with each other.

My use case is this:

I have sensors to detect when the player enters them to perform some action for things like teleporters or objects the player can pickup.

But there are something I want the player to be able to specifically "use" so when the player is i the use state I want to turn on a sensor that detects if it is within other sensors to be able to use the physics system to find what might be usable.

**Comment by spydon** [comment]
I don't think it is possible for sensors to detect sensors. You can use a body with a filter set so that it doesn't collide with the rest of the world for this instead.

**Comment by supagu** [comment]
thanks, that might just work.
