### ISSUE TITLE
Include generic for `world.createJoint`

### ISSUE THREAD

**Issue by alestiago** [flame-engine/forge2d#36]
# Problem to solve
Avoid casting when doing something as:

`PrismaticJoint prismaticJoint = world.createJoint(prismaticJointDef) as PrismaticJoint`

# Proposal
Use of generics to avoid casting:

`PrismaticJoint prismaticJoint = world.createJoint<PrismaticJoint>(prismaticJointDef)`

# More information

## Possible solutions
1. Updating [function](https://github.com/flame-engine/forge2d/blob/f54c61bf75a389812f3c764b32c4ee8195dddda1/lib/src/dynamics/world.dart#L166) signature to `T createJoint<T extends Joint>(JointDef def)` and return to `return joint as T;` (Simplest Solution)
2. Refactoring [`joint.dart`](https://github.com/flame-engine/forge2d/blob/f54c61bf75a389812f3c764b32c4ee8195dddda1/lib/src/dynamics/joints/joint.dart#L6) to perhaps benefit from OOP and simplify static method `static Joint create(World world, JointDef def)`
3. Open to further suggestions

---
I'm interested in working on a PR for this.

**Comment by erickzanardo** [comment]
Sounds good to me! Feel free to put a PR for it 🚀

**Comment by spydon** [comment]
Sounds good to me too, there are a lot of these things that have been passed along through all the ports from C++. I assigned you to the issue.
