### ISSUE TITLE
feat: deprecate `JointType` in favour of dart type system

### ISSUE THREAD

**Issue by alestiago** [flame-engine/forge2d#43]
# Problem to solve
Use of `JointType` enum is redundant or in many cases loses type inference.

# Proposal
Remove `JointType` enum in favour of dart type system to simplify the library.

# More information
I predict this would be a breaking change.

---
I'm interested in working on a PR for this.

**Comment by spydon** [comment]
Haha, same conclusion I had when reviewing your PR.
I assigned you to the issue.
