### ISSUE TITLE
Bug in `particle/particle_system.dart`

### ISSUE THREAD

**Issue by gkjpettet** [flame-engine/forge2d#68]
I think that the commented line (`particle/particle_system.dart` line 233) below needs deleting:

```dart
for (var y = (aabb.lowerBound.y / stride).floor() * stride;
          y < upperBoundY;
          y += stride) {
        for (var x = (aabb.lowerBound.x / stride).floor() * stride;
            x < upperBoundX;
            x += stride) {
          final p = _tempVec..setValues(x, y);
          if (shape.testPoint(identity, p)) {
            p.setFrom(Transform.mulVec2(transform, p));
            final particle = seedParticle.clone();
            p.sub(groupDef.position); // <---- This needs removing
            particle.position.setFrom(p);
            p.scaleOrthogonalInto(
              groupDef.angularVelocity,
              particle.velocity,
            );
            particle.velocity.add(groupDef.linearVelocity);
            createParticle(particle);
          }
        }
      }
```

By subtracting the group definition's position from the particle's position it causes all particles in the group being created to be centred around world position (0, 0). If you remove the commented line then any offset you apply to the group's position (via `GroupDef.position` is honoured. 

This bug is also present in JBox2D.

**Comment by spydon** [comment]
Makes sense, do you want to put up a PR with the fix?

**Comment by gkjpettet** [comment]
OK. I've created a pull request. This is my first one so apologies if I've not done it correctly.
