### ISSUE TITLE
`debugMode = true` does not show the purple info box

### ISSUE THREAD

**Issue by aytunch** [flame-engine/forge2d#74]
This works in flame components but not for forge2d bodies.
or I am missing something.
What is the recommended way to draw a bounding box for our `BodyComponent`s?
Thanks

**Comment by spydon** [comment]
`debugMode` for `BodyComponent` should render the fixtures in the body, the body doesn't have a bounding box in the same sense as a normal Flame component so we can't render that. 
If you want to create a method drawing a bounding box yourself you can get the AABB for each fixture and either render that directly, or you can add them together to get a bounding box for the whole body:
https://github.com/flame-engine/forge2d/blob/main/packages/forge2d/lib/src/dynamics/fixture.dart#L106-L112

**Comment by aytunch** [comment]
@spydon thank you for the reply. I understand now that `debugMode` does different things in a `FlameComponent` and a `BodyComponent`.
