### ISSUE TITLE
Link in readme is outdated

### ISSUE THREAD

**Issue by guyluz11** [flame-engine/forge2d#79]
The link in the readme is outdated since the repo moved from it to 
https://github.com/flame-engine/flame/tree/main/packages/flame_forge2d

https://github.com/flame-engine/forge2d/blob/5fc28abd5012e62d56b6a437796a772b2be13e8b/README.md?plain=1#L21

**Comment by spydon** [comment]
You don't have to open an issue for something this small if you intend to fix it with a PR, then the PR is enough. 😄
I'll close my PR so that I can merge yours. :)
