### ISSUE TITLE
bug: chain shape collisions throw error

### ISSUE THREAD

**Issue by naychrist** [flame-engine/forge2d#83]
hi there,
for my application I need to recreate a chain shape each frame based on some computer vision contour tracking. Works fine with polygons but wanted to use chain shapes as need concave hulls. However, when doing this I frequently get the this error despite the only fixtures colliding being the chain shape and some circles:

`Not compatible contact type, line 121 in 'package:forge2d/src/dynamics/contacts/contact.dart`

Note that the circles may be anywhere at the time the chain shape is drawn although I understand chain shape supports collision from both sides (I can remove circle objects manually if inside chain shape).  Any advice? My fallback would be to triangulate the poly and create multiple polys/tris but this is a lot more expensive.

**Comment by spydon** [comment]
No idea what that could be due to unfortunately, if you can find the issue we're of course open to PRs though. :)

**Comment by naychrist** [comment]
Apologies, I simplified my project to test and realised the error was actually happening when my chain shape collided with another hidden chain shape I created at the apps window edges. That's not something I need to try and accomodate so just added them to the a filter group to ignore collisions and all good. closing issue.
