### ISSUE TITLE
Question: Where is the "testbed"

### ISSUE THREAD

**Issue by MathiasDuus** [flame-engine/forge2d#87]
When I looked at the mousejoint in the code it says I have to look at the testbed if I want to learn how to use it.     
But where is the testbed?

**Comment by spydon** [comment]
It's probably an outdated comment, if you are using Flame there is an example of how to use it here:
https://examples.flame-engine.org/#/flame_forge2d%2Fjoints_MouseJoint
(You can get to the code by pressing `< >`)

**Comment by MathiasDuus** [comment]
Okay, thank you for the fast reply :)    
I will take a look there.
