### ISSUE TITLE
[Feature Request] Compatibility with Flame mixin HasGameReference

### ISSUE THREAD

**Issue by joshhammock** [flame-engine/forge2d#95]
Hello! Thank you for all the hard work on this project. It has become my package of choice for physics as a game maker!

Considering its common usage with Flame, would it be possible to integrate the Flame mixin HasGameReference?

**Comment by spydon** [comment]
It is already possible! :) 
Are you using flame_forge2d? The BodyComponent already uses that mixin, so you just have to pass the type of your game as generics to the BodyComponent when extending/creating it, to have a more specific game type available in the component.

**Comment by joshhammock** [comment]
Oh snap! I'm still learning, so this was new to me. Thank you for the info!
